plugins {
    id 'com.android.library'
    id 'org.jetbrains.kotlin.android'
    id 'org.jetbrains.kotlin.kapt'
}

group 'com.tangem.tangem_sdk'
version '1.0-SNAPSHOT'

def kotlin_version = '1.9.24'

android {
    namespace 'com.tamgen.tangem_sdk_flutter'

    compileSdkVersion 34

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = '17'
    }

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(17)
        }
    }

    tasks.withType(org.jetbrains.kotlin.gradle.tasks.KotlinCompile).configureEach {
        kotlinOptions {
            jvmTarget = "17"
        }
    }

    kapt {
        arguments {
            arg("jvmTarget", "17")
        }
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    defaultConfig {
        minSdkVersion 21
    }
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8:$kotlin_version"

    implementation "com.tangem.tangem-sdk-kotlin:android:releases-5.35-596"
    implementation "com.tangem.tangem-sdk-kotlin:core:releases-5.35-596"
    implementation 'com.squareup.moshi:moshi:1.12.0'
    implementation "com.squareup.moshi:moshi-kotlin:1.12.0"
    kapt("com.squareup.moshi:moshi-kotlin-codegen:1.12.0")

    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'androidx.core:core-ktx:1.10.1'
}